local new_logic = require("components/parambar/logic")
local parambar_defaults = require("components/parambar/defaults")

describe("parambar logic", function()
  local config, logic

  -- Runs frames until every bar has stopped animating, so assertions can talk
  -- about the settled picture. Guards against the runaway-easing bug.
  local function settle(limit)
    local plan
    for _ = 1, limit or 200 do
      plan = logic.tick()
      if not (plan.hp.dirty or plan.mp.dirty or plan.tp.dirty) then
        return plan
      end
    end
    error("bars never converged")
  end

  before_each(function()
    config = parambar_defaults(1920, 1080)
    logic = new_logic(config)
  end)

  describe("seeding and vitals", function()
    it("starts empty", function()
      local plan = settle()
      assert.are.equal(0, plan.hp.width)
      assert.is_true(plan.hp.hidden)
      assert.are.equal("0", plan.hp.text)
    end)

    it("takes the whole vitals table from the player", function()
      logic.seed({ hp = 1200, hpp = 100, mp = 300, mpp = 60, tp = 250 })
      local plan = settle()
      assert.are.equal("1200", plan.hp.text)
      assert.are.equal("300", plan.mp.text)
      assert.are.equal("250", plan.tp.text)
    end)

    it("takes single values from the change events", function()
      logic.set_vital("hpp", 50)
      logic.set_vital("hp", 600)
      local plan = settle()
      assert.are.equal("600", plan.hp.text)
      assert.are.equal(66, plan.hp.width)
    end)

    it("ignores a vital it does not know", function()
      assert.has_no.errors(function()
        logic.set_vital("wisdom", 5)
      end)
    end)

    it("survives a nil vitals table", function()
      assert.has_no.errors(function()
        logic.seed(nil)
      end)
    end)
  end)

  describe("bar widths", function()
    it("fills proportionally to the percent, floored", function()
      logic.seed({ hp = 100, hpp = 100, mp = 100, mpp = 50, tp = 0 })
      local plan = settle()
      assert.are.equal(132, plan.hp.width)
      assert.are.equal(66, plan.mp.width)
    end)

    it("derives the TP bar from tenths of TP, capped at a full bar", function()
      logic.set_vital("tp", 500)
      assert.are.equal(50, logic.tpp())
      logic.set_vital("tp", 3000)
      assert.are.equal(100, logic.tpp())
      local plan = settle()
      assert.are.equal(132, plan.tp.width)
    end)

    it("hides a bar that has emptied and shows it again when it refills", function()
      logic.seed({ hp = 100, hpp = 100 })
      assert.is_false(settle().hp.hidden)
      logic.set_vital("hpp", 0)
      assert.is_true(settle().hp.hidden)
      logic.set_vital("hpp", 100)
      assert.is_false(settle().hp.hidden)
    end)
  end)

  describe("easing", function()
    it("grows a tenth of the remaining distance per frame, rounded up", function()
      logic.seed({ hp = 1000, hpp = 100 })
      assert.are.equal(14, logic.tick().hp.width)
      assert.are.equal(26, logic.tick().hp.width)
    end)

    it("shrinks the same way", function()
      logic.seed({ hp = 1000, hpp = 100 })
      settle()
      logic.set_vital("hpp", 0)
      assert.are.equal(118, logic.tick().hp.width)
      assert.are.equal(106, logic.tick().hp.width)
    end)

    it("converges exactly on the target rather than overshooting", function()
      logic.seed({ hp = 1000, hpp = 100 })
      assert.are.equal(132, settle().hp.width)
      logic.set_vital("hpp", 0)
      assert.are.equal(0, settle().hp.width)
    end)

    it("stops being dirty once it converges", function()
      logic.seed({ hp = 1000, hpp = 100 })
      settle()
      assert.is_false(logic.tick().hp.dirty, "a converged bar must not re-ease every frame")
      assert.is_false(logic.tick().mp.dirty)
      assert.is_false(logic.tick().tp.dirty)
    end)

    it("becomes dirty again when a value changes", function()
      logic.seed({ hp = 1000, hpp = 100 })
      settle()
      logic.set_vital("hpp", 50)
      assert.is_true(logic.tick().hp.dirty)
      assert.is_false(logic.tick().mp.dirty, "only the bar that changed")
    end)

    it("re-eases towards a new width when the metrics change mid-animation", function()
      logic.seed({ hp = 1000, hpp = 100 })
      settle()
      logic.command({ "width", "40" })
      assert.are.equal(40, settle().hp.width)
    end)
  end)

  describe("text colouring", function()
    local function hp_state(hpp)
      logic.set_vital("hpp", hpp)
      return settle().hp.color_state
    end

    it("bands HP on strictly-less-than thresholds", function()
      assert.are.equal("normal", hp_state(75))
      assert.are.equal("yellow", hp_state(74))
      assert.are.equal("yellow", hp_state(50))
      assert.are.equal("orange", hp_state(49))
      assert.are.equal("orange", hp_state(25))
      assert.are.equal("red", hp_state(24))
      assert.are.equal("red", hp_state(0))
    end)

    it("bands MP the same way", function()
      logic.set_vital("mpp", 24)
      assert.are.equal("red", settle().mp.color_state)
      logic.set_vital("mpp", 80)
      assert.are.equal("normal", settle().mp.color_state)
    end)

    it("resolves the band to the colour configured for it", function()
      logic.set_vital("hpp", 10)
      assert.are.same(config.low_hp_colors.red, settle().hp.color)
      logic.set_vital("hpp", 100)
      local normal = settle().hp.color
      assert.are.same({ r = config.text_color.r, g = config.text_color.g, b = config.text_color.b }, normal)
    end)

    it("never bands TP, however low it is", function()
      logic.set_vital("tp", 0)
      assert.are.equal("normal", settle().tp.color_state)
    end)

    it("highlights TP from exactly 1000", function()
      logic.set_vital("tp", 999)
      assert.are.equal("normal", settle().tp.color_state)
      logic.set_vital("tp", 1000)
      assert.are.equal("full_tp", settle().tp.color_state)
      assert.are.same(config.full_tp_color, settle().tp.color)
      logic.set_vital("tp", 1001)
      assert.are.equal("full_tp", settle().tp.color_state)
    end)
  end)

  describe("bar dimming", function()
    it("dims only the TP bar below full TP", function()
      logic.seed({ hp = 1, hpp = 100, mp = 1, mpp = 100, tp = 999 })
      local plan = settle()
      assert.are.equal(180, plan.tp.alpha)
      assert.are.equal(255, plan.hp.alpha, "HP must not be dimmed as a side effect")
      assert.are.equal(255, plan.mp.alpha)
    end)

    it("brightens the TP bar at full TP", function()
      logic.set_vital("tp", 1000)
      assert.are.equal(255, settle().tp.alpha)
    end)

    it("leaves the TP bar bright when dimming is turned off", function()
      config.dim_tp_bar = false
      logic.set_vital("tp", 500)
      assert.are.equal(255, settle().tp.alpha)
    end)
  end)

  describe("death reconciliation", function()
    it("shows zero HP when the percent says dead, whatever the absolute stream said", function()
      logic.seed({ hp = 1200, hpp = 100 })
      settle()
      logic.set_vital("hpp", 0)
      local plan = settle()
      assert.are.equal("0", plan.hp.text)
      assert.are.equal("red", plan.hp.color_state)
    end)

    it("does the same for MP", function()
      logic.seed({ mp = 900, mpp = 100 })
      settle()
      logic.set_vital("mpp", 0)
      assert.are.equal("0", settle().mp.text)
    end)

    it("re-seeds both streams together", function()
      logic.set_vital("hp", 1200)
      logic.set_vital("hpp", 0)
      logic.seed({ hp = 500, hpp = 100, mp = 0, mpp = 0, tp = 0 })
      assert.are.equal("500", settle().hp.text)
    end)
  end)

  describe("metrics", function()
    it("uses the full-size set by default", function()
      local metrics = logic.metrics()
      assert.are.equal(132, metrics.bar_width)
      assert.are.equal(18, metrics.spacing)
      assert.are.equal(472, metrics.total_width)
      assert.are.equal("bar_bg.png", metrics.background)
    end)

    it("survives a hand-edited config that put a scalar where a metric set goes", function()
      config.bar = 5
      assert.has_no.errors(function()
        logic.tick()
      end)
      assert.are.equal(0, logic.metrics().bar_width)
    end)

    it("switches to the compact set and its own image width", function()
      config.compact = true
      local metrics = logic.metrics()
      assert.are.equal(116, metrics.bar_width)
      assert.are.equal(16, metrics.spacing)
      assert.are.equal(421, metrics.total_width, "the compact image is 421px wide")
      assert.are.equal("bar_compact.png", metrics.background)
    end)
  end)

  describe("geometry", function()
    it("lays the bars and numbers out against the background frame", function()
      local geometry = logic.geometry(100, 200, 1)
      assert.are.same({ x = 100, y = 200, width = 472, height = 24 }, geometry.background)
      assert.are.equal(115, geometry.bars[1].x)
      assert.are.equal(202, geometry.bars[1].y)
      assert.are.equal(8, geometry.bars[1].height)
      assert.are.equal(275, geometry.bars[2].x)
      assert.are.equal(435, geometry.bars[3].x)
      assert.are.equal(165, geometry.texts[1].x)
      assert.are.equal(202, geometry.texts[1].y)
      assert.are.equal(330, geometry.texts[2].x)
      assert.are.equal(490, geometry.texts[3].x)
      assert.are.equal(14, geometry.font_size)
    end)

    it("moves the fills with the bar offset and the numbers with the text offset", function()
      config.bar.offset = 5
      config.text_offset = 7
      local geometry = logic.geometry(100, 200, 1)
      assert.are.equal(120, geometry.bars[1].x)
      assert.are.equal(172, geometry.texts[1].x)
    end)

    it("multiplies every offset, size and font by the scale", function()
      local geometry = logic.geometry(100, 200, 2)
      assert.are.same({ x = 100, y = 200, width = 944, height = 48 }, geometry.background)
      assert.are.equal(130, geometry.bars[1].x)
      assert.are.equal(204, geometry.bars[1].y)
      assert.are.equal(16, geometry.bars[1].height)
      assert.are.equal(230, geometry.texts[1].x)
      assert.are.equal(28, geometry.font_size)
    end)

    it("rounds the font size to a whole number", function()
      assert.are.equal(18, logic.geometry(0, 0, 1.25).font_size)
    end)

    it("reports bounds matching the background frame", function()
      assert.are.same({ 100, 200, 472, 24 }, { logic.bounds(100, 200, 1) })
      assert.are.same({ 100, 200, 708, 36 }, { logic.bounds(100, 200, 1.5) })
    end)

    it("scales the eased fill width too", function()
      logic.seed({ hp = 100, hpp = 100 })
      assert.are.equal(264, logic.geometry(0, 0, 2).fill_width(settle().hp.width))
    end)
  end)

  describe("preview", function()
    it("shows sample vitals so an empty HUD can still be positioned", function()
      logic.set_preview(true)
      local plan = settle()
      assert.are.equal(99, plan.hp.width)
      assert.are.equal(66, plan.mp.width)
      assert.are.equal("full_tp", plan.tp.color_state)
    end)

    it("restores the live values on the way out", function()
      logic.seed({ hp = 42, hpp = 10, mp = 0, mpp = 0, tp = 0 })
      settle()
      logic.set_preview(true)
      settle()
      logic.set_preview(false)
      local plan = settle()
      assert.are.equal("42", plan.hp.text)
      assert.are.equal(13, plan.hp.width)
    end)

    it("keeps recording live changes while previewing", function()
      logic.set_preview(true)
      logic.set_vital("hp", 77)
      logic.set_vital("hpp", 100)
      logic.set_preview(false)
      assert.are.equal("77", settle().hp.text)
    end)
  end)

  describe("commands", function()
    it("reports the current metrics when asked for nothing", function()
      local message = logic.command({})
      assert.is_not_nil(message:find("132", 1, true))
      assert.is_not_nil(message:lower():find("compact"))
    end)

    it("sets width, spacing and offset on the active metric set", function()
      assert.is_true(select(2, logic.command({ "width", "200" })))
      assert.are.equal(200, config.bar.width)
      logic.command({ "spacing", "24" })
      assert.are.equal(24, config.bar.spacing)
      logic.command({ "offset", "3" })
      assert.are.equal(3, config.bar.offset)
      assert.are.equal(132, parambar_defaults(1920, 1080).bar.width, "defaults are untouched")
    end)

    it("writes to the compact set while compact mode is on", function()
      config.compact = true
      logic.command({ "width", "200" })
      assert.are.equal(200, config.compact_bar.width)
      assert.are.equal(132, config.bar.width)
    end)

    it("routes a metric write by the same rule metrics() reads by", function()
      config.compact = "yes"
      logic.command({ "width", "200" })
      assert.are.equal(200, config.bar.width, "only a real boolean means compact")
      assert.are.equal(116, config.compact_bar.width)
    end)

    it("toggles compact mode", function()
      assert.is_true(select(2, logic.command({ "compact", "on" })))
      assert.is_true(config.compact)
      logic.command({ "compact", "OFF" })
      assert.is_false(config.compact)
    end)

    it("refuses a width below the minimum", function()
      local message, changed = logic.command({ "width", "7" })
      assert.is_false(changed)
      assert.is_not_nil(message:find("8", 1, true))
      assert.are.equal(132, config.bar.width)
    end)

    it("accepts the minimum width", function()
      assert.is_true(select(2, logic.command({ "width", "8" })))
    end)

    it("refuses negative spacing and offset", function()
      assert.is_false(select(2, logic.command({ "spacing", "-1" })))
      assert.is_false(select(2, logic.command({ "offset", "-1" })))
      assert.is_true(select(2, logic.command({ "offset", "0" })))
    end)

    it("refuses values that are not whole numbers", function()
      assert.is_false(select(2, logic.command({ "width", "abc" })))
      assert.is_false(select(2, logic.command({ "width", "12.5" })))
      assert.is_false(select(2, logic.command({ "width" })))
    end)

    it("refuses numbers that are not plain decimal integers", function()
      assert.is_false(select(2, logic.command({ "width", "0x84" })))
      assert.is_false(select(2, logic.command({ "width", "1e2" })))
      assert.are.equal(132, config.bar.width)
    end)

    it("refuses anything but on or off for compact", function()
      local message, changed = logic.command({ "compact", "maybe" })
      assert.is_false(changed)
      assert.is_not_nil(message:lower():find("on"))
    end)

    it("hints instead of staying silent on an unknown verb", function()
      local message, changed = logic.command({ "wobble" })
      assert.is_false(changed)
      assert.is_not_nil(message:find("wobble", 1, true))
    end)

    it("matches verbs case-insensitively", function()
      assert.is_true(select(2, logic.command({ "WIDTH", "50" })))
    end)
  end)
end)
