local grammar = require("lib/actionbar/grammar")

describe("the address grammars", function()
  describe("the crossbar's", function()
    local g = grammar.crossbar()

    it("is two sides of eight slots over eight sets", function()
      assert.are.equal(8, g.set_count)
      assert.are.equal(8, g.slot_count)
      assert.are.same({ "left", "right" }, g.side_order)
      assert.are.equal("left", g.sides.l)
      assert.are.equal("right", g.sides.R)
    end)

    it("splits <set><L|R><slot> in either case, with or without a layer prefix", function()
      assert.are.same({ "", "1", "left", "1" }, { g.split("1L1") })
      assert.are.same({ "", "2", "right", "8" }, { g.split("2r8") })
      assert.are.same({ "sub", "1", "left", "6" }, { g.split("SUB:1L6") })
      assert.are.same({ "ctx:light-arts", "1", "left", "3" }, { g.split("ctx:light-arts:1L3") })
    end)

    it("refuses anything else", function()
      assert.is_nil(g.split("1:7"))
      assert.is_nil(g.split("L1"))
      assert.is_nil(g.split("1L"))
      assert.is_nil(g.split(7))
    end)

    it("labels an address the way it is typed", function()
      assert.are.equal("1L3", g.label(1, "left", 3))
      assert.are.equal("sub:2R8", g.label("sub:2", "right", 8))
    end)
  end)

  describe("the hotbar's", function()
    local g = grammar.hotbar()

    it("is one row of ten slots over eight sets", function()
      assert.are.equal(8, g.set_count)
      assert.are.equal(10, g.slot_count)
      assert.are.same({ "row" }, g.side_order)
      assert.are.equal("row", g.sides.row)
      assert.is_nil(g.sides.l)
    end)

    it("splits <set>:<slot>, with or without a layer prefix", function()
      assert.are.same({ "", "3", "row", "7" }, { g.split("3:7") })
      assert.are.same({ "", "3", "row", "10" }, { g.split("3:10") })
      assert.are.same({ "sub", "3", "row", "7" }, { g.split("sub:3:7") })
      assert.are.same({ "wpn", "13", "row", "7" }, { g.split("WPN:13:7") })
      assert.are.same({ "ctx:light-arts", "3", "row", "7" }, { g.split("ctx:light-arts:3:7") })
    end)

    it("refuses the crossbar's shape, a bare number, and a prefix with no colon of its own", function()
      assert.is_nil(g.split("3L7"))
      assert.is_nil(g.split("37"))
      assert.is_nil(g.split("3:"))
      assert.is_nil(g.split(":7"))
      assert.is_nil(g.split("wpn3:7"))
      assert.is_nil(g.split(":3:7"))
    end)

    it("labels an address with the colon", function()
      assert.are.equal("3:7", g.label(3, "row", 7))
      assert.are.equal("ctx:haste:3:10", g.label("ctx:haste:3", "row", 10))
    end)

    it("names its own form for the hints", function()
      assert.is_not_nil(g.form:find("<set>:<slot>", 1, true))
      assert.is_not_nil(grammar.crossbar().form:find("<set><L|R><slot>", 1, true))
    end)
  end)
end)
